### ISSUE TITLE
Error installing new Cisco appliance version 3745

### ISSUE THREAD

**Issue by JaapLaaij** [GNS3/gns3-registry#260]
Hi all,

Tried to vreate a new version for Cisco 3745 with ios:
c3745-adventerprisek9-mz.124-12.bin
The following error occured when installing the 'new' appliance:

Traceback (most recent call last):
  File "./gns3-gui\gns3\utils\wait_for_lambda_worker.py", line 66, in run
  File "./gns3-gui\gns3\utils\wait_for_lambda_worker.py", line 58, in run
  File "./gns3-gui\gns3\dialogs\appliance_wizard.py", line 406, in <lambda>
  File "./gns3-gui\gns3\registry\config.py", line 163, in add_appliance
  File "./gns3-gui\gns3\registry\config.py", line 199, in _add_dynamips_config
KeyError: 'idlepc'

**Comment by grossmj** [comment]
This has been fixed.
