### ISSUE TITLE
check.py error

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#416]
Running check.py on an Ubuntu 18.04 host complains for unicode characters in picture.py:
```
adosztal@lab:~/Documents/gns3-registry$ python check.py 
Traceback (most recent call last):
  File "check.py", line 24, in <module>
    from picture import get_size
  File "/home/adosztal/Documents/gns3-registry/picture.py", line 40
SyntaxError: Non-ASCII character '\xc2' in file /home/adosztal/Documents/gns3-registry/picture.py on line 40, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I changed these characters (copyright and double quotes) to ASCII versions but then I get his error:
```
adosztal@lab:~/Documents/gns3-registry$ python check.py 
Traceback (most recent call last):
  File "check.py", line 109, in <module>
    use_imagemagick = shutil.which("identify")
AttributeError: 'module' object has no attribute 'which'
```

I have shutil installed:
```
adosztal@lab:~/Documents/gns3-registry$ dpkg -l | grep shutil
ii  python-whichcraft                                           0.4.1-1                                      all          cross-platform cross-python shutil.which functionality (Python 2 module)
ii  python3-whichcraft                                          0.4.1-1                                      all          cross-platform cross-python shutil.which functionality (Python 3 module)
```

**Comment by b-ehlers** [comment]
The README is incorrect, you need Python3, not Python (2).

Using `python3 check.py` should solve both of your issues.

Nevertheless picture.py should get a `# -*- coding: utf-8 -*-` line, both here in gns3-registry as well in gns3-server.

**Comment by adosztal** [comment]
Much better. :) Thanks, @b-ehlers. I'll raise a PR with the fix.
