### ISSUE TITLE
Fresh clone/install - check.py traceback

### ISSUE THREAD

**Issue by nodenineinc** [GNS3/gns3-registry#568]
Brand new GNS3-VM image spun up (which is built upon Ubuntu 18.04.5) - https://www.gns3.com/software/download-vm

cloned a copy of this project & ran the pip3 install command and it reports everything successfully met.

```
==========
gns3:/opt/gns3/gns3-registry# pip3 install -r requirements.txt
Requirement already satisfied: jsonschema==2.5.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (2.5.1)
Requirement already satisfied: pycurl==7.21.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (7.21.5)
==========
```

run the "check.py" command and python soils it's britches.  ;)

```
==========
gns3:/opt/gns3/gns3-registry# python3 check.py
=> Check appliances
Check clearos.gns3a
Check jupyter27.gns3a
Check packetfence-zen.gns3a
Check fortigate.gns3a
Check openbsd.gns3a
Check fortiproxy.gns3a
Check chromium.gns3a
Check vpp.gns3a
Check cisco-3660.gns3a
Check frr.gns3a
Check cisco-fmcv.gns3a
Check cisco-csr1000v.gns3a
Check loadbalancer_org-va.gns3a
Check riverbed-steelhead-cx.gns3a
Check hp-vsr1001.gns3a
Check network_automation.gns3a
Check cisco-iou-l2.gns3a
Check juniper-vrr.gns3a
Check bird.gns3a
Check smoothwall.gns3a
Check puppy-linux.gns3a
Traceback (most recent call last):
  File "check.py", line 176, in <module>
    main()
  File "check.py", line 160, in main
    check_appliance(appliance)
  File "check.py", line 84, in check_appliance
    appliance_json = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 77 (char 602)
==========
```

**Comment by b-ehlers** [comment]
You made nothing wrong and check.py is working normally. This is just the way it reports faulty appliances.

> Check puppy-linux.gns3a
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 77 (char 602)

This tells you, that in puppy-linux.gns3a a ',' is missing in line 13 column 77. So I severely doubt, that this appliance is working.

This is not the only error, other appliance have issues as well.

**Comment by nodenineinc** [comment]
ah - thank you for the explanation.  I suppose a more clear/poignant error message could help possibly clarify the misunderstanding.  "Error in appliance file syntax" or whatnot.  Regardless, thank you though for taking the time to explain.  :)
